use tower_lsp::jsonrpc::Result;
use tower_lsp::lsp_types::*;
use tracing::trace;

use crate::{parser::Dependency, tools::MarkdownBuilder};

use super::{Clients, Document};

pub async fn get_cargo_hover(
    clients: &Clients,
    _doc: &Document,
    dep: &Dependency,
) -> Result<Option<Hover>> {
    let Some(version) = dep.spec().and_then(|s| s.contents.version.as_ref()) else {
        return Ok(None);
    };

    let dependency_name = dep.name().unquoted();
    let dependency_version = version.unquoted();

    // Add basic hover information with version and name
    trace!("Hovering: {dependency_name} version {dependency_version}");
    let mut md = MarkdownBuilder::new();
    md.h2(dependency_name);
    md.version(dependency_version);

    // Try to fetch additional information from the index - description, links
    trace!("Fetching crate data from crates.io");
    if let Ok(crate_data) = clients
        .crates
        .get_crate_data(dependency_name)
        .await
        .map(|c| c.inner)
    {
        md.br();
        md.p(crate_data.description);

        // Ignore homepage or docs if it's the same as the repo
        let mut docs = crate_data.links.documentation.as_deref();
        let mut page = crate_data.links.homepage.as_deref();
        let repo = crate_data.links.repository.as_deref();
        if page == repo {
            page = None;
        }
        if docs == repo {
            docs = None;
        }

        // Add links to documentation, repo, and homepage
        let docs_rs = format!("https://docs.rs/{}", crate_data.name);
        md.br();
        md.h3("Links");
        if let Some(docs) = docs {
            md.a("Documentation", docs);
            if !docs.contains("docs.rs") {
                // docs.rs is the standard for autogenerated documentation
                // for any rust crate, so we always provide it at the end,
                // will be formatted like "- Documentation (docs.rs)" with
                // both of those links being clickable by the user
                md.extend_last(format!(" ([docs.rs]({docs_rs}))"));
            }
        } else {
            md.a("Documentation", docs_rs);
        }
        if let Some(repo) = repo {
            md.a("Repository", repo);
        }
        if let Some(page) = page {
            md.a("Homepage", page);
        }
    }

    Ok(Some(Hover {
        range: Some(dep.range()),
        contents: HoverContents::Markup(MarkupContent {
            kind: MarkupKind::Markdown,
            value: md.build(),
        }),
    }))
}
